#!/bin/bash

rofi -theme ~/.config/rofi/appmnu.rasi \
        -lines 12 \
        -padding 18 \
        -width 60 \
        -location 0 \
        -show drun \
        -sidebar-mode \
        -columns 3  \
        -show-icons \
        -drun-icon-theme


