#!/bin/sh

[ $(paru -Qu 2>/dev/null | grep -v ignored | cut -d' ' -f1 | sort | comm -3 - <(sort ~/PKG-SKIP 2>/dev/null) | wc -l) -gt 0 ] && \
    paru -Qu 2>/dev/null | \
    grep -v ignored | \
    cut -d' ' -f1 | sort | \
    comm -3 - <(sort ~/PKG-SKIP 2>/dev/null) | wc -l | \
    xargs -r -I {} echo " %{F#A9B665}  %{F#FBF1C7}{}" || echo " %{F#EA6962} %{F#FBF1C7}0"

