#!/bin/sh

# ##############################################################################
# #                                  ENV VARS                                  # 
# ##############################################################################

# export BROWSER=vivaldi-stable

pgrep -x sxhkd > /dev/null || sxhkd &

# ##############################################################################
# #                                  FUNCTIONS                                 # 
# ##############################################################################

# Credits to 6gk/polka
rule() { bspc rule -a "$@" & }
config() { bspc config "$@" & }

# ##############################################################################
# #                                AUTOSTART APPS                              #
# ##############################################################################

# Autostart Apps
dunst &
$HOME/.local/bin/eww daemon &
mpd
# $HOME/.local/bin/mpd-discord-rpc &
picom &

# Start polkit agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Set wallpaper
hsetroot -fill "$HOME/.wallpaper.png"

# Start polybar
sh $HOME/.config/polybar/launch.sh
setxkbmap br abnt2
# I hate mouse drift.
# xset mouse 2.5 0

# ##############################################################################
# #                                 WINDOW RULES                               #
# ##############################################################################


# ##############################################################################
# #                            GENERAL CONFIGURATION                           #
# ##############################################################################

bspc monitor -d I II III IV V

config pointer_modifier             Mod4

config border_width                 3
config window_gap                   10

config top_padding                  30
config bottom_padding               0

config split_ratio                  0.62
config borderless_monocle           true
config gapless_monocle              true

# Yes, this is stolen from gk.
outer   =  '0x1d2021'   # outer
inner1  =  '0x32302f'  # focused
inner2  =  '0x282828'  # normal

targets() {
 	case $1 in
		focused) bspc query -N -n .local.focused.\!fullscreen;;
		normal)  bspc query -N -n .local.\!focused.\!fullscreen
	esac | grep -iv "$v"
}

draw() { chwb2 -I "$inner" -O "$outer" -i "4" -o "9" $* |:; }

initial draw, and then subscribe to events
{ echo; bspc subscribe node_geometry node_focus; } |
 	while read -r _; do
		[ "$v" ] || v='abcdefg'
		inner=$inner1 draw "$(targets focused)"
		inner=$inner2 draw "$(targets normal)"
    done
