#!/bin/sh

# ##############################################################################
# #                                  ENV VARS                                  # 
# ##############################################################################

# export BROWSER=vivaldi-stable

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep bspswallow > /dev/null || $HOME/.local/scripts/bspswallow &

# ##############################################################################
# #                                  FUNCTIONS                                 # 
# ##############################################################################

# Credits to 6gk/polka
rule() { bspc rule -a "$@" & }
config() { bspc config "$@" & }

# ##############################################################################
# #                                AUTOSTART APPS                              #
# ##############################################################################

# Autostart Apps
xrdb $HOME/.Xresources &
killall "dusnt"
dunst &
$HOME/.local/scripts/eww daemon &
mpd &
# $HOME/.local/bin/mpd-discord-rpc &
picom &

# Start polkit agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Set wallpaper
hsetroot -fill "$HOME/.wallpaper.png"

# Start polybar
sh $HOME/.config/polybar/launch.sh
setxkbmap br abnt2

# ##############################################################################
# #                                 WINDOW RULES                               #
# ##############################################################################

# ##############################################################################
# #                            GENERAL CONFIGURATION                           #
# ##############################################################################

bspc monitor -d I II III IV 

bspc config pointer_modifier             Mod4
bspc config pointer_action1              move
bspc config pointer_action2              resize_side
bspc config pointer_action3              resize_corner

bspc config border_width                 3
bspc config window_gap                   10

bspc config top_padding                  30
bspc config bottom_padding               0

bspc config split_ratio                  0.55
bspc config borderless_monocle           true
bspc config gapless_monocle              true
bspc config single_monocle               true

# Yes, this is stolen from gk.
outer   =  '0x1d2021'   # outer
inner1  =  '0x32302f'  # focused
inner2  =  '0x282828'  # normal

targets() {
 	case $1 in
		focused) bspc query -N -n .local.focused.\!fullscreen;;
		normal)  bspc query -N -n .local.\!focused.\!fullscreen
	esac | grep -iv "$v"
}

draw() { chwb2 -I "$inner" -O "$outer" -i "4" -o "9" $* |:; }

initial draw, and then subscribe to events
{ echo; bspc subscribe node_geometry node_focus; } |
 	while read -r _; do
		[ "$v" ] || v='abcdefg'
		inner=$inner1 draw "$(targets focused)"
		inner=$inner2 draw "$(targets normal)"
    done
